export const receptionsTypes = {
  GET_ALL_RECEPTIONS: "GET_ALL_RECEPTIONS",
  SET_SELECTED_RECEPTION: "SET_SELECTED_RECEPTION",
  SET_SORT_BY: "SET_SORT_BY",
  SET_FILTER_BY: "SET_FILTER_BY",
  IS_SHOW_FILTER: "IS_SHOW_FILTER",
};
